sudo: false

language: node_js

matrix:
  include:
    - node_js: "12"
    - node_js: "14"
    - node_js: "18"
      env: COVERALLS=1

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then npm run coveralls; fi
