// Generated by CoffeeScript 2.3.1
(function() {
  var double, i, j, k, link;

  for (i = j = 1; j <= 3; i = ++j) {
    console.log("direct", i);
  }

  (borschik.include("./f.js"))("whatever");

  if (true) {
    console.log('always');
  }

  link = borschik.link("./f.js");

  double = (x) => {
    return x + x;
  };

  console.log(double("borschik:include:./b.js"));

  for (i = k = 2; k >= -1; i = --k) {
    console.log("reversed", i);
  }

  borschik.include("./c.js");

  die();

}).call(this);

//# sourceMappingURL=coffee.js.map
