// Generated by CoffeeScript 2.3.1
(function() {
  var double, i, j, k, link;

  for (i = j = 1; j <= 3; i = ++j) {
    console.log("direct", i);
  }

  (function f(x) {
    console.log("f:" + x);
})("whatever");

  if (true) {
    console.log('always');
  }

  link = "f.js";

  double = (x) => {
    return x + x;
  };

  console.log(double("bar"));

  for (i = k = 2; k >= -1; i = --k) {
    console.log("reversed", i);
  }

  const c = 'baz';

function die() {
    throw new Error('DIE!');
}
;

  die();

}).call(this);

//# sourceMappingURL=coffee.js.map
